"""create anki_card table

Revision ID: 199997b32b16
Revises:
Create Date: 2025-07-07 08:37:03.443063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '199997b32b16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ankicard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('front', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('back', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ankicard')
    # ### end Alembic commands ###
